version: "3.8"

services:
    postgres:
        container_name: "caseritos-postgres"
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_PASSWORD=secret
        volumes:
            - postgres_db:/var/lib/postgresql/data

volumes:
    postgres_db:
